[2025-07-09T05:05:17.375+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:05:17.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:05:17.532+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:05:17.533+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-09T05:05:17.566+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:05:17.594+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'load_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpx1w98qpd']
[2025-07-09T05:05:17.600+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:05:17.601+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load_task
[2025-07-09T05:05:17.601+0000] {standard_task_runner.py:63} INFO - Started process 229 to run task
[2025-07-09T05:05:17.752+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:05:17.966+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:05:17.968+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:05:18.272+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into MySQL
[2025-07-09T05:05:18.273+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:05:18.274+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:05:18.357+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=load_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T050517, end_date=20250709T050518
[2025-07-09T05:05:18.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:05:18.445+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:05:18.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
